### ISSUE TITLE
No matching version found for kareem@2.0.3

### ISSUE THREAD

**Issue by spaggh** [vkarpov15/kareem#11]
I can't install version 2.0.3 of kareem.

`npm show kareem version` return `2.0.3`
but
`npm install kareem@2.0.3` return

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for kareem@2.0.3
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```
It's to install the latest version of Mongoose !

It works with 2.0.2

**Comment by spaggh** [comment]
Update "package-lock.json" file to 2.0.3 ???

**Comment by vkarpov15** [comment]
Bumped 2.0.4 with lockfile changes: https://github.com/vkarpov15/kareem/commit/2ab02939287f8fe96d2fa1894fb79c20ceff66dc
