### ISSUE TITLE
[URGENT] Broken backward compatibility

### ISSUE THREAD

**Issue by b1f6c1c4** [vkarpov15/kareem#12]
Version [v2.0.5](https://github.com/vkarpov15/kareem/commit/5afc5b9ab34f82702c8cd3a700c0f67fdfe4c86d) introduces a performance optimization for `createWrapper`. However, this BREAKS backward compatibility:

```js
const Kareem = require('kareem');
const hooks = new Kareem();

const cook = hooks.createWrapper(
  'cook',
  (callback) => {
    callback(null, { });
  },
);

hooks.pre('cook', (next) => {
  console.log('evil');
  next();
});

cook((error, result) => {
  console.log('done');
});
```

v2.0.4 output:
```
evil
done
```

v2.0.5 output:
```
done
```

**Comment by vkarpov15** [comment]
This is a very good point, will fix ASAP. I'm curious, how did you run into this issue? I don't think you can trigger this problem from mongoose...

**Comment by b1f6c1c4** [comment]
@vkarpov15 Actually, this issue comes from my npm package [jest-mongoose](https://github.com/b1f6c1c4/jest-mongoose), in which I [inject](https://github.com/b1f6c1c4/jest-mongoose/blob/master/index.js#L23) hooks AFTER model compilation but BEFORE running test suites. That's why this issue arises.

**Comment by vkarpov15** [comment]
Then that's a bit of a problem, because mongoose doesn't support modifying hooks after the model is compiled. I can patch kareem by adding a flag to support the old behavior of `createWrapper()`, but it won't help you because mongoose will continue to use the new behavior. The performance benefits of this fast path are substantial (Automattic/mongoos#6126), and the internal hooks object is not part of mongoose's public API.

**Comment by b1f6c1c4** [comment]
IMO it'd be better for me to re-`applyHooks` after injecting hooks to benefit from the performance in production env and maintain the testability in test env. I'll try that first and, if that works, I'll close this issue.

**Comment by vkarpov15** [comment]
Yeah in mongoose 5 our applyHooks logic just runs createWrapper on mongoose's internal helpers. Just rerunning createWrapper should work for now

**Comment by vkarpov15** [comment]
https://github.com/Automattic/mongoose/blob/master/lib/services/model/applyHooks.js
