### ISSUE TITLE
I like this package, but It doesn't support wrapping an async function. Can I patch it?

### ISSUE THREAD

**Issue by yunshansimon** [vkarpov15/kareem#13]
I have forked and upgraded this package, adding more features like:
1.  wrap async/promise function.
2. short-cut by pre-hook.
3. force wrap function even without hooks.
4. unit test for new features.
[the source](https://github.com/yunshansimon/kareem)
Can I pull the new upgrade?

**Comment by edgardleal** [comment]
I think this issue could be closed

**Comment by vkarpov15** [comment]
Yes this issue can we closed. We already have support for async functions from 05b4480824598fb838fa6f3ac49f60625e29eb16 so I think we've already got most of this.
