### ISSUE TITLE
[Docs] it's not clear what `done` refers to in execPre(...) examples

### ISSUE THREAD

**Issue by AbdelrahmanHafez** [vkarpov15/kareem#14]
In the first example of the docs, what does `done` refer to? I thought it was a missing parameter for the callback parameter that's passed to execPre(...), but I noticed it's consistently not mentioned everywhere where `execPre(...)` is used.

**Comment by vkarpov15** [comment]
Fixed. The `done()` in the examples is Mocha's `done()`, because we generate the README examples from our mocha tests.
