### ISSUE TITLE
Promise support on post hooks

### ISSUE THREAD

**Issue by biomorgoth** [vkarpov15/kareem#15]
I see on the README doc that specifically pre hooks support returning Promises

https://github.com/vkarpov15/kareem/tree/4f3524b9e9ac15c2bb74f30d47d1294ce7d58ba7#it-supports-returning-a-promise

> You can also return a promise from your pre hooks instead of calling next(). When the returned promise resolves, kareem will kick off the next middleware.

But it does not say anything related to post hooks. Nevertheless, i found on source code that there seems to be support for promises on post hooks, as seen on:

- `execPost`: https://github.com/vkarpov15/kareem/blob/4f3524b9e9ac15c2bb74f30d47d1294ce7d58ba7/index.js#L204
- post unit tests: https://github.com/vkarpov15/kareem/blob/4f3524b9e9ac15c2bb74f30d47d1294ce7d58ba7/test/post.test.js#L150

Even tested it with a simple script which seemed to behave correctly:

```javascript
const Kareem = require('kareem')
const sleep = ms => new Promise(res => setTimeout(res, ms))

const hooks = new Kareem()

hooks.pre('foo', async function() {
  console.log('pre first sleep')
  await sleep(2000)
  console.log('pre first sleep complete')
})

hooks.pre('foo', async function() {
  console.log('pre second sleep')
  await sleep(2000)
  console.log('pre second sleep complete')
})

hooks.post('foo', async function() {
  console.log('post first sleep')
  await sleep(2000)
  console.log('post first sleep complete')
})

hooks.post('foo', async function() {
  console.log('post second sleep')
  await sleep(2000)
  console.log('post second sleep complete')
})

const foo = hooks.createWrapper('foo', function(cb) {
  console.log('foo sleep')
  sleep(2000).then(_ => {
    console.log('foo sleep complete')
    cb()
  })
})

foo(_ => console.log('finished!'))
```

Now, is there a reason this feature is not publicly documented? Maybe deprecated or unstable? Should i trust using this feature? If not it would be nice to explicitly show the feature on README.md

**Comment by vkarpov15** [comment]
We support returning promises from post hooks - it didn't seem necessary to document this because we documented that pre hooks support returning promises. But I agree, we added a note in the README to be explicit.

**Comment by biomorgoth** [comment]
Great! Thank you for answering this.
